#!/bin/sh
set -e

echo "WELL.."

. /usr/share/debconf/confmodule
db_version 2.0
db_capb
db_title 'Mint Debian Mirrors'
db_input high 'mint-debian-mirrors/choose-mirror'
db_go                        
db_stop

exit 0
